<?php

namespace Noopstudios\MarketingSMS\Tests;

use Noopstudios\MarketingSMS\marketingSMS;

class MarketingSMSPhpTest extends \PHPUnit\Framework\TestCase
{
    public function setUp(): void
    {
        $this->apiToken = Fixtures::$apiToken;
        $this->sandboxUrl = Fixtures::$sandboxUrl;
        $this->name = Fixtures::$name;
        $this->message = Fixtures::$message;
        $this->from = Fixtures::$from;
        $this->phones = Fixtures::$phones;

        //parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_works_as_expected(){
        $marketingsms = new marketingSMS($this->apiToken, $this->sandboxUrl);

        $params = [
            'name' => $this->name,
            'message' => $this->message,
            'from' => $this->from,
            'phones' => $this->phones,
        ];

        $response = $marketingsms->sendMessage($params);

        $this->assertEquals($response['http_code'], 200);
    }


}